// spikes/manage-web/vue/src/App.vue
<script setup lang="ts">
import {
  computed,
  onBeforeUnmount,
  ref,
  shallowRef,
  watch,
  type Component,
} from "vue";
import {
  Activity,
  AlertTriangle,
  Check,
  ClipboardCheck,
  FileOutput,
  Gauge,
  GitBranch,
  ListTree,
  Logs,
  Pencil,
  RefreshCw,
  RotateCcw,
  Settings2,
  ShieldCheck,
  SquareActivity,
  X,
} from "lucide-vue-next";
import {
  ADD_TRANSFORM_PATCH,
  ENTER_EDIT_MODE_PATCHES,
  STATUS_UPDATE_PATCH,
  createLogLine,
  createOperation,
  type OperationState,
  type TreeNode,
  type TreePatch,
} from "@manage-spike/shared";
import ConfigurationPanel from "./ConfigurationPanel.vue";
import LogViewer from "./LogViewer.vue";
import OperationDrawer from "./OperationDrawer.vue";
import ResourceTree from "./ResourceTree.vue";
import { useManageTree } from "./useManageTree";

type WorkspaceTab = "overview" | "configuration" | "activity" | "logs" | "output";

interface TabDefinition {
  id: WorkspaceTab;
  label: string;
  icon: Component;
}

const tabs: ReadonlyArray<TabDefinition> = [
  { id: "overview", label: "Overview", icon: Gauge },
  { id: "configuration", label: "Configuration", icon: Settings2 },
  { id: "activity", label: "Activity", icon: Activity },
  { id: "logs", label: "Logs", icon: Logs },
  { id: "output", label: "Output", icon: FileOutput },
];

const {
  state,
  announcement,
  insertedIds,
  transitioning,
  applyPatch,
  applyPatches,
} = useManageTree();

const selectedId = ref("resource-proxy");
const focusedId = ref("resource-proxy");
const activeTab = ref<WorkspaceTab>("overview");
const logRunning = ref(false);
const logLines = shallowRef<ReadonlyArray<string>>([]);
const operations = shallowRef<ReadonlyArray<OperationState>>([createOperation()]);

let logIndex = 0;
let logTimer: ReturnType<typeof setInterval> | undefined;
let operationTimer: ReturnType<typeof setInterval> | undefined;

const selectedNode = computed(
  () => state.value.nodes[selectedId.value] ?? state.value.nodes["resource-proxy"],
);

const canAddTransform = computed(
  () =>
    state.value.mode === "edit" &&
    !!state.value.nodes["config-replayer"] &&
    !state.value.nodes["config-transform"] &&
    !transitioning.value,
);

const diagnostics = computed<ReadonlyArray<TreeNode>>(() => {
  const selected = selectedNode.value;
  if (!selected) {
    return [];
  }
  const result: TreeNode[] = [];
  function visit(nodeId: string): void {
    const node = state.value.nodes[nodeId];
    if (!node) {
      return;
    }
    if (node.kind === "diagnostic") {
      result.push(node);
    }
    node.childIds.forEach(visit);
  }
  selected.childIds.forEach(visit);
  return result;
});

watch(logRunning, (running) => {
  if (logTimer) {
    clearInterval(logTimer);
    logTimer = undefined;
  }
  if (running) {
    logTimer = setInterval(() => {
      logLines.value = [
        ...logLines.value.slice(-149),
        createLogLine(logIndex++),
      ];
    }, 420);
  }
});

operationTimer = setInterval(() => {
  operations.value = operations.value.map((operation) => {
    if (operation.state !== "running") {
      return operation;
    }
    const progress = Math.min(operation.progress + 8, 92);
    return progress >= 92
      ? {
          ...operation,
          progress,
          state: "waiting",
          phase: "Waiting for cluster state",
        }
      : { ...operation, progress };
  });
}, 760);

onBeforeUnmount(() => {
  if (logTimer) {
    clearInterval(logTimer);
  }
  if (operationTimer) {
    clearInterval(operationTimer);
  }
});

function enterEditMode(): void {
  if (state.value.mode === "inspect" && !transitioning.value) {
    applyPatches(ENTER_EDIT_MODE_PATCHES);
  }
}

function persistentAncestor(nodeId: string): string {
  let current = state.value.nodes[nodeId];
  while (current?.parentId && current.kind.startsWith("config")) {
    current = state.value.nodes[current.parentId];
  }
  return current?.id ?? "resource-proxy";
}

function leaveEditMode(): void {
  if (state.value.mode !== "edit" || transitioning.value) {
    return;
  }
  const patches: TreePatch[] = [];
  if (state.value.nodes["config-proxy"]) {
    patches.push({
      type: "remove",
      nodeId: "config-proxy",
      announce: "Capture proxy configuration closed.",
    });
  }
  if (state.value.nodes["config-replayer"]) {
    patches.push({
      type: "remove",
      nodeId: "config-replayer",
      announce: "Traffic replayer configuration closed.",
    });
  }
  patches.push({
    type: "set-mode",
    mode: "inspect",
    announce: "Returned to live resource inspection.",
  });

  if (selectedNode.value?.kind.startsWith("config")) {
    selectedId.value = persistentAncestor(selectedId.value);
  }
  const focused = state.value.nodes[focusedId.value];
  if (focused?.kind.startsWith("config")) {
    focusedId.value = persistentAncestor(focusedId.value);
  }
  applyPatches(patches);
}

function addTransform(): void {
  if (canAddTransform.value) {
    applyPatches([ADD_TRANSFORM_PATCH]);
  }
}

function selectNode(nodeId: string): void {
  selectedId.value = nodeId;
  const node = state.value.nodes[nodeId];
  if (node?.kind === "config-field" || node?.kind === "config-group") {
    activeTab.value = "configuration";
  }
}

function startLogs(): void {
  activeTab.value = "logs";
  logRunning.value = true;
}

function beginOperation(label: string, phase: string): void {
  const operation: OperationState = {
    id: `operation-${Date.now()}`,
    label,
    phase,
    state: "running",
    progress: 12,
  };
  operations.value = [
    operation,
    ...operations.value,
  ].slice(0, 4);
  activeTab.value = "activity";
}

function performCapability(
  capability: NonNullable<TreeNode["capabilities"]>[number],
): void {
  if (capability === "edit") {
    enterEditMode();
  } else if (capability === "logs") {
    startLogs();
  } else if (capability === "output") {
    activeTab.value = "output";
  } else if (capability === "approve") {
    beginOperation(`Approve ${selectedNode.value?.label}`, "Submitting approval");
  } else if (capability === "reset") {
    beginOperation(`Plan reset for ${selectedNode.value?.label}`, "Calculating reset plan");
  }
}

const capabilityDetails = {
  edit: { label: "Edit", icon: Pencil },
  approve: { label: "Approve", icon: ShieldCheck },
  reset: { label: "Reset", icon: RotateCcw },
  logs: { label: "Logs", icon: Logs },
  output: { label: "Output", icon: FileOutput },
} as const;
</script>

<template>
  <div class="app-shell">
    <header class="app-header">
      <div class="brand">
        <span class="brand-mark">
          <SquareActivity :size="19" aria-hidden="true" />
        </span>
        <div>
          <h1>Workflow Manage</h1>
          <span>migration · ma-demo</span>
        </div>
      </div>

      <div class="header-state">
        <span class="run-state"><span /> Running</span>
        <span>Observed just now</span>
      </div>

      <div class="header-actions">
        <button
          class="icon-button"
          type="button"
          data-testid="refresh-control"
          aria-label="Simulate status refresh"
          title="Simulate status refresh"
          @click="applyPatch(STATUS_UPDATE_PATCH)"
        >
          <RefreshCw :size="16" aria-hidden="true" />
        </button>
        <button
          class="button secondary"
          type="button"
          data-testid="edit-mode-control"
          :disabled="transitioning"
          @click="state.mode === 'edit' ? leaveEditMode() : enterEditMode()"
        >
          <X v-if="state.mode === 'edit'" :size="16" aria-hidden="true" />
          <Pencil v-else :size="16" aria-hidden="true" />
          {{ state.mode === "edit" ? "Leave edit mode" : "Edit configuration" }}
        </button>
        <button
          class="button primary"
          type="button"
          :disabled="state.mode !== 'edit' || transitioning"
          @click="beginOperation('Review pending configuration', 'Checking schema and cluster state')"
        >
          <ClipboardCheck :size="16" aria-hidden="true" />
          Review changes
        </button>
      </div>
    </header>

    <div class="main-layout">
      <ResourceTree
        :state="state"
        :selected-id="selectedNode?.id ?? 'resource-proxy'"
        :focused-id="focusedId"
        :inserted-ids="insertedIds"
        @select="selectNode"
        @focus-change="focusedId = $event"
      />

      <main v-if="selectedNode" class="workspace">
        <div class="workspace-header">
          <div class="selection-heading">
            <span class="selection-icon" :data-severity="selectedNode.severity">
              <GitBranch :size="19" aria-hidden="true" />
            </span>
            <div>
              <div class="selection-context">
                {{ selectedNode.kind.replace("-", " ") }} ·
                {{ selectedNode.phase ?? selectedNode.severity }}
              </div>
              <h2>{{ selectedNode.label }}</h2>
              <p>{{ selectedNode.description ?? "Workflow resource" }}</p>
            </div>
          </div>
          <div class="selection-actions" aria-label="Resource actions">
            <button
              v-for="capability in selectedNode.capabilities"
              :key="capability"
              class="button tertiary"
              type="button"
              :disabled="capability === 'edit' && (state.mode === 'edit' || transitioning)"
              @click="performCapability(capability)"
            >
              <component :is="capabilityDetails[capability].icon" :size="16" aria-hidden="true" />
              {{ capabilityDetails[capability].label }}
            </button>
          </div>
        </div>

        <div class="workspace-tabs" role="tablist" aria-label="Resource details">
          <button
            v-for="tab in tabs"
            :id="`tab-${tab.id}`"
            :key="tab.id"
            role="tab"
            type="button"
            :aria-selected="activeTab === tab.id"
            :tabindex="activeTab === tab.id ? 0 : -1"
            @click="activeTab = tab.id"
          >
            <component :is="tab.icon" :size="16" aria-hidden="true" />
            {{ tab.label }}
            <span
              v-if="tab.id === 'logs' && logRunning"
              class="tab-live-dot"
              aria-label="streaming"
            />
          </button>
        </div>

        <section
          class="workspace-content"
          role="tabpanel"
          :aria-labelledby="`tab-${activeTab}`"
        >
          <div v-if="activeTab === 'overview'" class="overview">
            <dl class="facts-grid">
              <div><dt>Phase</dt><dd>{{ selectedNode.phase ?? "Not started" }}</dd></div>
              <div><dt>Status</dt><dd :data-severity="selectedNode.severity">{{ selectedNode.severity }}</dd></div>
              <div><dt>Current value</dt><dd>{{ selectedNode.valueSummary ?? "No value reported" }}</dd></div>
              <div><dt>Resource ID</dt><dd class="mono">{{ selectedNode.id }}</dd></div>
            </dl>

            <section class="detail-section">
              <h3>Diagnostics</h3>
              <details v-for="diagnostic in diagnostics" :key="diagnostic.id" class="diagnostic-item">
                <summary>
                  <AlertTriangle :size="16" aria-hidden="true" />
                  <span>{{ diagnostic.label }}</span>
                  <span>{{ diagnostic.severity }}</span>
                </summary>
                <p>{{ diagnostic.description }}</p>
                <strong>{{ diagnostic.diagnostic }}</strong>
              </details>
              <div v-if="diagnostics.length === 0" class="inline-empty">
                <Check :size="17" aria-hidden="true" />
                No diagnostics for this selection.
              </div>
            </section>

            <section class="detail-section">
              <h3>Dependencies</h3>
              <div class="dependency-row">
                <span>capture-proxy</span><i /><span>captured-traffic</span><i /><strong>{{ selectedNode.label }}</strong>
              </div>
            </section>
          </div>

          <ConfigurationPanel
            v-else-if="activeTab === 'configuration'"
            :state="state"
            :selected-node="selectedNode"
            :can-add-transform="canAddTransform"
            :transform-added="!!state.nodes['config-transform']"
            @add-transform="addTransform"
          />

          <div v-else-if="activeTab === 'activity'" class="activity-list">
            <div v-for="operation in operations" :key="operation.id" class="activity-row">
              <span :data-state="operation.state" />
              <div><strong>{{ operation.label }}</strong><p>{{ operation.phase }}</p></div>
              <small>{{ operation.state }}</small>
            </div>
          </div>

          <LogViewer
            v-else-if="activeTab === 'logs'"
            :lines="logLines"
            :running="logRunning"
            @start="logRunning = true"
            @stop="logRunning = false"
            @clear="logLines = []"
          />

          <div v-else class="output-panel">
            <div class="output-stage"><span>01</span><div><strong>Evaluate capture</strong><p>Target compatibility and prerequisites</p></div><b>Complete</b></div>
            <div class="output-stage"><span>02</span><div><strong>Migrate live traffic</strong><p>Capture, buffer, transform, and replay</p></div><b>Running</b></div>
            <pre><code>target:
  endpoint: search-target:9200
replay:
  accepted: 14,208
  failed: 3</code></pre>
          </div>
        </section>
      </main>

      <OperationDrawer :operations="operations" />
    </div>

    <div class="sr-only" aria-live="polite" aria-atomic="true">
      {{ announcement }}
    </div>
  </div>
</template>

// spikes/manage-web/react/src/App.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Activity,
  AlertTriangle,
  Check,
  ClipboardCheck,
  FileOutput,
  Gauge,
  ListTree,
  Logs,
  Pencil,
  RefreshCw,
  RotateCcw,
  Settings2,
  ShieldCheck,
  SquareActivity,
  X,
} from "lucide-react";
import {
  ADD_TRANSFORM_PATCH,
  ENTER_EDIT_MODE_PATCHES,
  STATUS_UPDATE_PATCH,
  createLogLine,
  createOperation,
  type OperationState,
  type TreeNode,
  type TreePatch,
} from "@manage-spike/shared";
import { ConfigurationPanel } from "./ConfigurationPanel";
import { LogViewer } from "./LogViewer";
import { OperationDrawer } from "./OperationDrawer";
import { ResourceTree } from "./ResourceTree";
import { useManageTree } from "./useManageTree";

type WorkspaceTab = "overview" | "configuration" | "activity" | "logs" | "output";

const TABS: ReadonlyArray<{
  id: WorkspaceTab;
  label: string;
  icon: typeof Gauge;
}> = [
  { id: "overview", label: "Overview", icon: Gauge },
  { id: "configuration", label: "Configuration", icon: Settings2 },
  { id: "activity", label: "Activity", icon: Activity },
  { id: "logs", label: "Logs", icon: Logs },
  { id: "output", label: "Output", icon: FileOutput },
];

function collectDiagnostics(
  nodes: Readonly<Record<string, TreeNode>>,
  node: TreeNode,
): ReadonlyArray<TreeNode> {
  const diagnostics: TreeNode[] = [];
  const visit = (nodeId: string): void => {
    const current = nodes[nodeId];
    if (!current) {
      return;
    }
    if (current.kind === "diagnostic") {
      diagnostics.push(current);
    }
    current.childIds.forEach(visit);
  };
  node.childIds.forEach(visit);
  return diagnostics;
}

function Overview({
  node,
  nodes,
}: {
  node: TreeNode;
  nodes: Readonly<Record<string, TreeNode>>;
}) {
  const diagnostics = collectDiagnostics(nodes, node);
  return (
    <div className="overview">
      <dl className="facts-grid">
        <div>
          <dt>Phase</dt>
          <dd>{node.phase ?? "Not started"}</dd>
        </div>
        <div>
          <dt>Status</dt>
          <dd className={`status-text status-${node.severity}`}>
            {node.severity}
          </dd>
        </div>
        <div>
          <dt>Current value</dt>
          <dd>{node.valueSummary ?? "No value reported"}</dd>
        </div>
        <div>
          <dt>Resource ID</dt>
          <dd className="mono">{node.id}</dd>
        </div>
      </dl>
      <section className="detail-section">
        <h3>Diagnostics</h3>
        {diagnostics.length > 0 ? (
          <div className="diagnostic-list">
            {diagnostics.map((diagnostic) => (
              <details className="diagnostic-item" key={diagnostic.id}>
                <summary>
                  <AlertTriangle aria-hidden="true" />
                  <span>{diagnostic.label}</span>
                  <span className="diagnostic-severity">
                    {diagnostic.severity}
                  </span>
                </summary>
                <p>{diagnostic.description}</p>
                {diagnostic.diagnostic ? (
                  <strong>{diagnostic.diagnostic}</strong>
                ) : null}
              </details>
            ))}
          </div>
        ) : (
          <div className="inline-empty">
            <Check aria-hidden="true" />
            No diagnostics for this selection.
          </div>
        )}
      </section>
      <section className="detail-section dependency-section">
        <h3>Dependencies</h3>
        <div className="dependency-row">
          <span>capture-proxy</span>
          <span className="dependency-line" />
          <span>captured-traffic</span>
          <span className="dependency-line" />
          <strong>{node.label}</strong>
        </div>
      </section>
    </div>
  );
}

function ActivityPanel({
  operations,
}: {
  operations: ReadonlyArray<OperationState>;
}) {
  return (
    <div className="activity-list">
      {operations.map((operation) => (
        <div className="activity-row" key={operation.id}>
          <span className={`activity-marker activity-${operation.state}`} />
          <div>
            <strong>{operation.label}</strong>
            <p>{operation.phase}</p>
          </div>
          <span>{operation.state}</span>
        </div>
      ))}
      <div className="activity-row">
        <span className="activity-marker activity-succeeded" />
        <div>
          <strong>Capture proxy observed</strong>
          <p>Cluster state matched the submitted configuration.</p>
        </div>
        <span>18 min ago</span>
      </div>
    </div>
  );
}

function OutputPanel() {
  return (
    <div className="output-panel">
      <div className="output-stage">
        <span className="stage-order">01</span>
        <div>
          <strong>Evaluate capture</strong>
          <p>Target compatibility and capture prerequisites</p>
        </div>
        <span className="stage-state success">Complete</span>
      </div>
      <div className="output-stage">
        <span className="stage-order">02</span>
        <div>
          <strong>Migrate live traffic</strong>
          <p>Capture, buffer, transform, and replay</p>
        </div>
        <span className="stage-state running">Running</span>
      </div>
      <pre className="structured-output">
        <code>{`target:
  endpoint: search-target:9200
replay:
  accepted: 14,208
  failed: 3
  checkpoint: 2026-08-11T14:22:38Z`}</code>
      </pre>
    </div>
  );
}

function getPersistentAncestor(
  nodeId: string,
  nodes: Readonly<Record<string, TreeNode>>,
): string {
  let current = nodes[nodeId];
  while (current?.parentId && current.kind.startsWith("config")) {
    current = nodes[current.parentId];
  }
  return current?.id ?? "resource-proxy";
}

export function App() {
  const {
    state,
    announcement,
    insertedIds,
    transitioning,
    applyPatch,
    applyPatches,
  } = useManageTree();
  const [selectedId, setSelectedId] = useState("resource-proxy");
  const [focusedId, setFocusedId] = useState("resource-proxy");
  const [activeTab, setActiveTab] = useState<WorkspaceTab>("overview");
  const [logRunning, setLogRunning] = useState(false);
  const [logLines, setLogLines] = useState<ReadonlyArray<string>>([]);
  const [operations, setOperations] = useState<ReadonlyArray<OperationState>>(
    () => [createOperation()],
  );

  const selectedNode =
    state.nodes[selectedId] ?? state.nodes["resource-proxy"];
  const canAddTransform =
    state.mode === "edit" &&
    !!state.nodes["config-replayer"] &&
    !state.nodes["config-transform"] &&
    !transitioning;

  useEffect(() => {
    if (!logRunning) {
      return;
    }
    const interval = window.setInterval(() => {
      setLogLines((current) => [
        ...current.slice(-149),
        createLogLine(current.length),
      ]);
    }, 420);
    return () => window.clearInterval(interval);
  }, [logRunning]);

  useEffect(() => {
    const interval = window.setInterval(() => {
      setOperations((current) =>
        current.map((operation) => {
          if (operation.state !== "running") {
            return operation;
          }
          const progress = Math.min(operation.progress + 9, 92);
          return progress >= 92
            ? {
                ...operation,
                progress,
                state: "waiting",
                phase: "Waiting for cluster state",
              }
            : { ...operation, progress };
        }),
      );
    }, 720);
    return () => window.clearInterval(interval);
  }, []);

  const beginOperation = useCallback((label: string, phase: string): void => {
    const operation: OperationState = {
      id: `operation-${Date.now()}`,
      label,
      phase,
      state: "running",
      progress: 12,
    };
    setOperations((current) => [operation, ...current].slice(0, 4));
  }, []);

  const enterEditMode = (): void => {
    if (state.mode === "inspect" && !transitioning) {
      applyPatches(ENTER_EDIT_MODE_PATCHES);
    }
  };

  const leaveEditMode = (): void => {
    if (state.mode !== "edit" || transitioning) {
      return;
    }
    const patches: TreePatch[] = [];
    if (state.nodes["config-proxy"]) {
      patches.push({
        type: "remove",
        nodeId: "config-proxy",
        announce: "Capture proxy configuration closed.",
      });
    }
    if (state.nodes["config-replayer"]) {
      patches.push({
        type: "remove",
        nodeId: "config-replayer",
        announce: "Traffic replayer configuration closed.",
      });
    }
    patches.push({
      type: "set-mode",
      mode: "inspect",
      announce: "Returned to live resource inspection.",
    });

    if (selectedNode.kind.startsWith("config")) {
      setSelectedId(getPersistentAncestor(selectedId, state.nodes));
    }
    const focusedNode = state.nodes[focusedId];
    if (focusedNode?.kind.startsWith("config")) {
      setFocusedId(getPersistentAncestor(focusedId, state.nodes));
    }
    applyPatches(patches);
  };

  const addTransform = (): void => {
    if (canAddTransform) {
      applyPatches([ADD_TRANSFORM_PATCH]);
    }
  };

  const performCapability = (capability: NonNullable<TreeNode["capabilities"]>[number]) => {
    if (capability === "edit") {
      enterEditMode();
    } else if (capability === "logs") {
      setActiveTab("logs");
      setLogRunning(true);
    } else if (capability === "output") {
      setActiveTab("output");
    } else if (capability === "approve") {
      beginOperation(`Approve ${selectedNode.label}`, "Submitting approval");
      setActiveTab("activity");
    } else if (capability === "reset") {
      beginOperation(`Plan reset for ${selectedNode.label}`, "Calculating reset plan");
      setActiveTab("activity");
    }
  };

  const capabilityDetails = {
    edit: { label: "Edit", icon: Pencil },
    approve: { label: "Approve", icon: ShieldCheck },
    reset: { label: "Reset", icon: RotateCcw },
    logs: { label: "Logs", icon: Logs },
    output: { label: "Output", icon: FileOutput },
  } as const;

  const workspacePanel = useMemo(() => {
    if (activeTab === "overview") {
      return <Overview node={selectedNode} nodes={state.nodes} />;
    }
    if (activeTab === "configuration") {
      return (
        <ConfigurationPanel
          state={state}
          selectedNode={selectedNode}
          canAddTransform={canAddTransform}
          transformAdded={!!state.nodes["config-transform"]}
          onAddTransform={addTransform}
        />
      );
    }
    if (activeTab === "activity") {
      return <ActivityPanel operations={operations} />;
    }
    if (activeTab === "logs") {
      return (
        <LogViewer
          lines={logLines}
          running={logRunning}
          onStart={() => setLogRunning(true)}
          onStop={() => setLogRunning(false)}
          onClear={() => setLogLines([])}
        />
      );
    }
    return <OutputPanel />;
  }, [
    activeTab,
    canAddTransform,
    logLines,
    logRunning,
    operations,
    selectedNode,
    state,
  ]);

  return (
    <div className="app-shell">
      <header className="app-header">
        <div className="brand-block">
          <span className="brand-mark">
            <SquareActivity aria-hidden="true" />
          </span>
          <div>
            <h1>Workflow Manage</h1>
            <span>migration · ma-demo</span>
          </div>
        </div>
        <div className="header-state">
          <span className="run-state">
            <span />
            Running
          </span>
          <span className="observed-time">Observed just now</span>
        </div>
        <div className="header-actions">
          <button
            className="icon-button"
            type="button"
            data-testid="refresh-control"
            aria-label="Simulate status refresh"
            title="Simulate status refresh"
            onClick={() => applyPatch(STATUS_UPDATE_PATCH)}
          >
            <RefreshCw aria-hidden="true" />
          </button>
          <button
            className={`button ${state.mode === "edit" ? "danger-subtle" : "secondary"}`}
            type="button"
            data-testid="edit-mode-control"
            disabled={transitioning}
            onClick={state.mode === "edit" ? leaveEditMode : enterEditMode}
          >
            {state.mode === "edit" ? (
              <X aria-hidden="true" />
            ) : (
              <Pencil aria-hidden="true" />
            )}
            {state.mode === "edit" ? "Leave edit mode" : "Edit configuration"}
          </button>
          <button
            className="button primary"
            type="button"
            disabled={state.mode !== "edit" || transitioning}
            onClick={() =>
              beginOperation(
                "Review pending configuration",
                "Checking schema and cluster state",
              )
            }
          >
            <ClipboardCheck aria-hidden="true" />
            Review changes
          </button>
        </div>
      </header>

      <div className="main-layout">
        <ResourceTree
          state={state}
          selectedId={selectedNode.id}
          focusedId={focusedId}
          insertedIds={insertedIds}
          onSelect={setSelectedId}
          onFocusChange={setFocusedId}
        />

        <main className="workspace">
          <div className="workspace-header">
            <div className="selection-heading">
              <span className={`selection-icon severity-${selectedNode.severity}`}>
                <ListTree aria-hidden="true" />
              </span>
              <div>
                <div className="selection-context">
                  <span>{selectedNode.kind.replace("-", " ")}</span>
                  <span>·</span>
                  <span>{selectedNode.phase ?? selectedNode.severity}</span>
                </div>
                <h2>{selectedNode.label}</h2>
                <p>{selectedNode.description ?? "Workflow resource"}</p>
              </div>
            </div>
            <div className="selection-actions" aria-label="Resource actions">
              {selectedNode.capabilities?.map((capability) => {
                const details = capabilityDetails[capability];
                const Icon = details.icon;
                return (
                  <button
                    className="button tertiary"
                    type="button"
                    key={capability}
                    disabled={
                      capability === "edit" &&
                      (state.mode === "edit" || transitioning)
                    }
                    onClick={() => performCapability(capability)}
                  >
                    <Icon aria-hidden="true" />
                    {details.label}
                  </button>
                );
              })}
            </div>
          </div>

          <div className="workspace-tabs" role="tablist" aria-label="Resource details">
            {TABS.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  id={`tab-${tab.id}`}
                  role="tab"
                  type="button"
                  key={tab.id}
                  aria-selected={activeTab === tab.id}
                  aria-controls={`panel-${tab.id}`}
                  tabIndex={activeTab === tab.id ? 0 : -1}
                  onClick={() => setActiveTab(tab.id)}
                >
                  <Icon aria-hidden="true" />
                  {tab.label}
                  {tab.id === "logs" && logRunning ? (
                    <span className="tab-live-dot" aria-label="streaming" />
                  ) : null}
                </button>
              );
            })}
          </div>
          <div
            className="workspace-content"
            id={`panel-${activeTab}`}
            role="tabpanel"
            aria-labelledby={`tab-${activeTab}`}
          >
            {workspacePanel}
          </div>
        </main>

        <OperationDrawer operations={operations} />
      </div>
      <div className="sr-only" aria-live="polite" aria-atomic="true">
        {announcement}
      </div>
    </div>
  );
}
