// spikes/manage-web/react/src/LogViewer.tsx
import { useEffect, useRef } from "react";
import { Pause, Play, Trash2 } from "lucide-react";

interface LogViewerProps {
  lines: ReadonlyArray<string>;
  running: boolean;
  onStart: () => void;
  onStop: () => void;
  onClear: () => void;
}

export function LogViewer({
  lines,
  running,
  onStart,
  onStop,
  onClear,
}: LogViewerProps) {
  const tailRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (running) {
      tailRef.current?.scrollIntoView({ block: "end" });
    }
  }, [lines, running]);

  return (
    <div className="logs-tool">
      <div className="logs-toolbar">
        <div className="log-source">
          <span className={running ? "pulse-dot" : "idle-dot"} />
          <div>
            <strong>traffic-replayer</strong>
            <span>replayer-0 · migration-console</span>
          </div>
        </div>
        <div className="toolbar-actions">
          <button
            className={`button ${running ? "danger-subtle" : "primary"}`}
            type="button"
            data-testid="log-stream-control"
            onClick={running ? onStop : onStart}
          >
            {running ? <Pause aria-hidden="true" /> : <Play aria-hidden="true" />}
            {running ? "Stop stream" : "Start stream"}
          </button>
          <button
            className="icon-button"
            type="button"
            data-testid="log-clear-control"
            aria-label="Clear logs"
            title="Clear logs"
            disabled={lines.length === 0}
            onClick={onClear}
          >
            <Trash2 aria-hidden="true" />
          </button>
        </div>
      </div>
      <div className="log-output" role="log" aria-label="Resource logs">
        {lines.length === 0 ? (
          <span className="log-placeholder">Log stream is stopped.</span>
        ) : (
          lines.map((line, index) => (
            <div key={`${index}-${line}`} className="log-line">
              <span>{String(index + 1).padStart(3, "0")}</span>
              <code>{line}</code>
            </div>
          ))
        )}
        <div ref={tailRef} />
      </div>
    </div>
  );
}

// spikes/manage-web/vue/src/LogViewer.vue
<script setup lang="ts">
import { nextTick, ref, watch } from "vue";
import { Pause, Play, Trash2 } from "lucide-vue-next";

const props = defineProps<{
  lines: ReadonlyArray<string>;
  running: boolean;
}>();

const emit = defineEmits<{
  start: [];
  stop: [];
  clear: [];
}>();

const output = ref<HTMLElement>();

watch(
  () => props.lines.length,
  async () => {
    if (!props.running) {
      return;
    }
    await nextTick();
    if (output.value) {
      output.value.scrollTop = output.value.scrollHeight;
    }
  },
);
</script>

<template>
  <div class="logs-tool">
    <div class="logs-toolbar">
      <div class="log-source">
        <span :class="running ? 'pulse-dot' : 'idle-dot'" />
        <div>
          <strong>traffic-replayer</strong>
          <span>replayer-0 · migration-console</span>
        </div>
      </div>
      <div class="toolbar-actions">
        <button
          class="button"
          :class="running ? 'danger-subtle' : 'primary'"
          type="button"
          data-testid="log-stream-control"
          @click="running ? emit('stop') : emit('start')"
        >
          <Pause v-if="running" :size="16" aria-hidden="true" />
          <Play v-else :size="16" aria-hidden="true" />
          {{ running ? "Stop stream" : "Start stream" }}
        </button>
        <button
          class="icon-button"
          type="button"
          aria-label="Clear logs"
          title="Clear logs"
          :disabled="lines.length === 0"
          @click="emit('clear')"
        >
          <Trash2 :size="16" aria-hidden="true" />
        </button>
      </div>
    </div>
    <div ref="output" class="log-output" role="log" aria-label="Resource logs">
      <span v-if="lines.length === 0" class="log-placeholder">
        Log stream is stopped.
      </span>
      <div v-for="(line, index) in lines" v-else :key="`${index}-${line}`" class="log-line">
        <span>{{ String(index + 1).padStart(3, "0") }}</span>
        <code>{{ line }}</code>
      </div>
    </div>
  </div>
</template>
