// spikes/manage-web/react/src/OperationDrawer.tsx
import { CheckCircle2, CircleDashed, Clock3 } from "lucide-react";
import { type OperationState } from "@manage-spike/shared";

interface OperationDrawerProps {
  operations: ReadonlyArray<OperationState>;
}

function OperationIcon({ operation }: { operation: OperationState }) {
  if (operation.state === "succeeded") {
    return <CheckCircle2 aria-hidden="true" />;
  }
  if (operation.state === "running") {
    return <CircleDashed className="spin-slow" aria-hidden="true" />;
  }
  return <Clock3 aria-hidden="true" />;
}

export function OperationDrawer({ operations }: OperationDrawerProps) {
  const activeCount = operations.filter(
    (operation) => operation.state !== "succeeded",
  ).length;

  return (
    <aside className="operations-drawer" aria-label="Operations">
      <div className="operations-header">
        <div>
          <h2>Operations</h2>
          <span>{activeCount} active</span>
        </div>
        <span className="live-indicator">
          <span />
          Live
        </span>
      </div>
      <div className="operation-list">
        {operations.map((operation) => (
          <article className="operation-item" key={operation.id}>
            <div className="operation-icon">
              <OperationIcon operation={operation} />
            </div>
            <div className="operation-content">
              <div className="operation-title">
                <strong>{operation.label}</strong>
                <span>{operation.state}</span>
              </div>
              <p>{operation.phase}</p>
              <div
                className="progress-track"
                role="progressbar"
                aria-label={`${operation.label} progress`}
                aria-valuenow={operation.progress}
                aria-valuemin={0}
                aria-valuemax={100}
              >
                <span style={{ width: `${operation.progress}%` }} />
              </div>
            </div>
          </article>
        ))}
      </div>
    </aside>
  );
}

// spikes/manage-web/vue/src/OperationDrawer.vue
<script setup lang="ts">
import { Activity, CircleDashed } from "lucide-vue-next";
import type { OperationState } from "@manage-spike/shared";

defineProps<{
  operations: ReadonlyArray<OperationState>;
}>();
</script>

<template>
  <aside class="operations-drawer" aria-label="Active operations">
    <header>
      <div>
        <span class="eyebrow">Session</span>
        <h2>Operations</h2>
      </div>
      <span class="live-indicator">
        <span />
        Live
      </span>
    </header>
    <div class="operation-list">
      <article v-for="operation in operations" :key="operation.id" class="operation-item">
        <div class="operation-title">
          <span class="operation-icon">
            <CircleDashed
              v-if="operation.state !== 'succeeded'"
              :size="17"
              class="spinning"
              aria-hidden="true"
            />
            <Activity v-else :size="17" aria-hidden="true" />
          </span>
          <div>
            <strong>{{ operation.label }}</strong>
            <p>{{ operation.phase }}</p>
          </div>
          <span class="operation-state">{{ operation.state }}</span>
        </div>
        <div class="operation-progress" aria-label="Operation progress">
          <span :style="{ width: `${operation.progress}%` }" />
        </div>
        <footer>
          <span>{{ operation.progress }}%</span>
          <span>Cluster watch active</span>
        </footer>
      </article>
    </div>
  </aside>
</template>
