// migrationConsole/web/src/features/tree/ResourceTree.tsx
import {
  memo,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent,
} from "react";
import { ChevronDown, ChevronRight, Search } from "lucide-react";

import type { ManageNode, ManageSnapshot } from "../../api/client";


interface VisibleRow {
  node: ManageNode;
  depth: number;
}


interface ResourceTreeProps {
  snapshot: ManageSnapshot;
  selectedId: string | null;
  onSelect: (nodeId: string) => void;
}


function descendants(
  snapshot: ManageSnapshot,
  nodeId: string,
  target: Set<string>,
) {
  const node = snapshot.nodes[nodeId];
  if (!node) return;
  target.add(nodeId);
  node.childIds.forEach((childId) => descendants(snapshot, childId, target));
}


function filterIds(snapshot: ManageSnapshot, query: string): Set<string> | null {
  const normalized = query.trim().toLocaleLowerCase();
  if (!normalized) return null;
  const visible = new Set<string>();
  Object.values(snapshot.nodes).forEach((node) => {
    const searchable = [
      node.label,
      node.description,
      node.phase,
      node.status,
      node.valueSummary,
    ]
      .filter(Boolean)
      .join(" ")
      .toLocaleLowerCase();
    if (!searchable.includes(normalized)) return;
    descendants(snapshot, node.id, visible);
    let parentId = node.parentId;
    while (parentId) {
      visible.add(parentId);
      parentId = snapshot.nodes[parentId]?.parentId;
    }
  });
  return visible;
}


function visibleRows(
  snapshot: ManageSnapshot,
  expanded: ReadonlySet<string>,
  query: string,
): VisibleRow[] {
  const included = filterIds(snapshot, query);
  const rows: VisibleRow[] = [];
  const visit = (nodeId: string, depth: number) => {
    const node = snapshot.nodes[nodeId];
    if (!node || (included && !included.has(nodeId))) return;
    rows.push({ node, depth });
    if (included || expanded.has(nodeId)) {
      node.childIds.forEach((childId) => visit(childId, depth + 1));
    }
  };
  snapshot.rootIds.forEach((rootId) => visit(rootId, 1));
  return rows;
}


interface TreeRowProps {
  row: VisibleRow;
  expanded: boolean;
  inserted: boolean;
  focused: boolean;
  selected: boolean;
  onExpand: (nodeId: string) => void;
  onFocus: (nodeId: string) => void;
  onKeyDown: (event: KeyboardEvent<HTMLDivElement>, nodeId: string) => void;
  onSelect: (nodeId: string) => void;
  rowRef: (nodeId: string, element: HTMLDivElement | null) => void;
}


const TreeRow = memo(function TreeRow({
  row,
  expanded,
  inserted,
  focused,
  selected,
  onExpand,
  onFocus,
  onKeyDown,
  onSelect,
  rowRef,
}: TreeRowProps) {
  const { node, depth } = row;
  const expandable = node.childIds.length > 0;
  return (
    <div
      aria-expanded={expandable ? expanded : undefined}
      aria-label={`${node.label}, ${node.phase ?? node.status}`}
      aria-level={depth}
      aria-selected={selected}
      className={[
        "tree-row",
        `status-${node.status}`,
        selected ? "selected" : "",
        inserted ? "inserted" : "",
      ].join(" ")}
      data-node-id={node.id}
      onClick={() => onSelect(node.id)}
      onFocus={() => onFocus(node.id)}
      onKeyDown={(event) => onKeyDown(event, node.id)}
      ref={(element) => rowRef(node.id, element)}
      role="treeitem"
      style={{ "--tree-depth": depth } as React.CSSProperties}
      tabIndex={focused ? 0 : -1}
    >
      {expandable ? (
        <button
          aria-label={`${expanded ? "Collapse" : "Expand"} ${node.label}`}
          className="tree-expander"
          onClick={(event) => {
            event.stopPropagation();
            onExpand(node.id);
          }}
          tabIndex={-1}
          type="button"
        >
          {expanded ? <ChevronDown /> : <ChevronRight />}
        </button>
      ) : (
        <span className="tree-expander-spacer" />
      )}
      <span className="status-dot" aria-hidden="true" />
      <span className="tree-row-copy">
        <strong>{node.label}</strong>
        <span>{node.valueSummary ?? node.phase ?? node.kind}</span>
      </span>
      {node.diagnostics.length > 0 ? (
        <span className="diagnostic-count" aria-label={`${node.diagnostics.length} diagnostics`}>
          {node.diagnostics.length}
        </span>
      ) : null}
    </div>
  );
});


export function ResourceTree({
  snapshot,
  selectedId,
  onSelect,
}: ResourceTreeProps) {
  const [filter, setFilter] = useState("");
  const [expanded, setExpanded] = useState<Set<string>>(
    () => new Set(),
  );
  const [focusedId, setFocusedId] = useState<string | null>(selectedId);
  const [insertedIds, setInsertedIds] = useState<Set<string>>(() => new Set());
  const knownIds = useRef<Set<string> | null>(null);
  const rowElements = useRef(new Map<string, HTMLDivElement>());

  useEffect(() => {
    setExpanded((current) => {
      const next = new Set(
        [...current].filter((nodeId) => snapshot.nodes[nodeId]),
      );
      Object.values(snapshot.nodes).forEach((node) => {
        if (
          node.childIds.length > 0
          && (node.kind === "section" || node.kind === "group")
        ) {
          next.add(node.id);
        }
      });
      return next;
    });
  }, [snapshot]);

  useEffect(() => {
    const nextIds = new Set(Object.keys(snapshot.nodes));
    if (knownIds.current) {
      const inserted = new Set(
        [...nextIds].filter((nodeId) => !knownIds.current?.has(nodeId)),
      );
      if (inserted.size > 0) {
        setInsertedIds(inserted);
        const timer = window.setTimeout(() => setInsertedIds(new Set()), 450);
        knownIds.current = nextIds;
        return () => window.clearTimeout(timer);
      }
    }
    knownIds.current = nextIds;
  }, [snapshot]);

  const rows = useMemo(
    () => visibleRows(snapshot, expanded, filter),
    [snapshot, expanded, filter],
  );

  useEffect(() => {
    if (focusedId && snapshot.nodes[focusedId]) return;
    setFocusedId(selectedId ?? rows[0]?.node.id ?? null);
  }, [focusedId, rows, selectedId, snapshot.nodes]);

  const focusRow = useCallback((nodeId: string) => {
    setFocusedId(nodeId);
    rowElements.current.get(nodeId)?.focus();
  }, []);

  const handleKeyDown = useCallback((
    event: KeyboardEvent<HTMLDivElement>,
    nodeId: string,
  ) => {
    const index = rows.findIndex((row) => row.node.id === nodeId);
    const node = snapshot.nodes[nodeId];
    let targetId: string | undefined;
    if (event.key === "ArrowDown") targetId = rows[index + 1]?.node.id;
    if (event.key === "ArrowUp") targetId = rows[index - 1]?.node.id;
    if (event.key === "Home") targetId = rows[0]?.node.id;
    if (event.key === "End") targetId = rows.at(-1)?.node.id;
    if (event.key === "ArrowRight" && node.childIds.length > 0) {
      if (!expanded.has(nodeId)) {
        setExpanded((current) => new Set(current).add(nodeId));
      } else {
        targetId = node.childIds[0];
      }
    }
    if (event.key === "ArrowLeft") {
      if (expanded.has(nodeId)) {
        setExpanded((current) => {
          const next = new Set(current);
          next.delete(nodeId);
          return next;
        });
      } else {
        targetId = node.parentId ?? undefined;
      }
    }
    if (event.key === "Enter" || event.key === " ") {
      onSelect(nodeId);
    }
    if (targetId || [
      "ArrowDown",
      "ArrowUp",
      "ArrowLeft",
      "ArrowRight",
      "Home",
      "End",
      "Enter",
      " ",
    ].includes(event.key)) {
      event.preventDefault();
    }
    if (targetId) focusRow(targetId);
  }, [expanded, focusRow, onSelect, rows, snapshot.nodes]);

  const toggleExpanded = useCallback((nodeId: string) => {
    setExpanded((current) => {
      const next = new Set(current);
      if (next.has(nodeId)) next.delete(nodeId);
      else next.add(nodeId);
      return next;
    });
  }, []);

  const rowRef = useCallback((
    nodeId: string,
    element: HTMLDivElement | null,
  ) => {
    if (element) rowElements.current.set(nodeId, element);
    else rowElements.current.delete(nodeId);
  }, []);

  return (
    <>
      <label className="tree-filter">
        <Search aria-hidden="true" />
        <span className="sr-only">Filter resources</span>
        <input
          aria-label="Filter resources"
          onChange={(event) => setFilter(event.target.value)}
          placeholder="Filter resources"
          type="search"
          value={filter}
        />
      </label>
      <div className="tree-scroll" data-testid="tree-scroller">
        <div aria-label="Workflow resources" className="resource-tree" role="tree">
          {rows.map((row) => (
            <TreeRow
              expanded={expanded.has(row.node.id) || filter.length > 0}
              focused={focusedId === row.node.id}
              inserted={insertedIds.has(row.node.id)}
              key={row.node.id}
              onExpand={toggleExpanded}
              onFocus={setFocusedId}
              onKeyDown={handleKeyDown}
              onSelect={onSelect}
              row={row}
              rowRef={rowRef}
              selected={selectedId === row.node.id}
            />
          ))}
          {rows.length === 0 ? (
            <p className="tree-empty">No resources match this filter.</p>
          ) : null}
        </div>
      </div>
    </>
  );
}

// spikes/manage-web/vue/src/ResourceTree.vue
<script setup lang="ts">
import {
  computed,
  nextTick,
  shallowRef,
  watch,
  type ComponentPublicInstance,
} from "vue";
import {
  AlertCircle,
  AlertTriangle,
  CheckCircle2,
  ChevronRight,
  CircleDashed,
  FileSliders,
  Folder,
  Search,
  Workflow,
} from "lucide-vue-next";
import {
  DEFAULT_EXPANDED_IDS,
  type ManageTreeState,
  type TreeNode,
} from "@manage-spike/shared";

interface VisibleRow {
  node: TreeNode;
  depth: number;
  expanded: boolean;
}

const props = defineProps<{
  state: ManageTreeState;
  selectedId: string;
  focusedId: string;
  insertedIds: ReadonlySet<string>;
}>();

const emit = defineEmits<{
  select: [nodeId: string];
  focusChange: [nodeId: string];
}>();

const filter = shallowRef("");
const expandedIds = shallowRef<ReadonlySet<string>>(
  new Set(DEFAULT_EXPANDED_IDS),
);
const rowElements = new Map<string, HTMLElement>();

function nodeMatches(node: TreeNode, query: string): boolean {
  return [
    node.label,
    node.description,
    node.phase,
    node.valueSummary,
    node.diagnostic,
  ]
    .filter(Boolean)
    .join(" ")
    .toLocaleLowerCase()
    .includes(query);
}

const rows = computed<ReadonlyArray<VisibleRow>>(() => {
  const query = filter.value.trim().toLocaleLowerCase();
  const matches = new Map<string, boolean>();

  function branchMatches(nodeId: string): boolean {
    const cached = matches.get(nodeId);
    if (cached !== undefined) {
      return cached;
    }
    const node = props.state.nodes[nodeId];
    const result =
      !!node &&
      (nodeMatches(node, query) ||
        node.childIds.some((childId) => branchMatches(childId)));
    matches.set(nodeId, result);
    return result;
  }

  const visible: VisibleRow[] = [];
  function visit(nodeId: string, depth: number): void {
    const node = props.state.nodes[nodeId];
    if (!node || (query && !branchMatches(nodeId))) {
      return;
    }
    const expanded = query.length > 0 || expandedIds.value.has(nodeId);
    visible.push({ node, depth, expanded });
    if (expanded) {
      node.childIds.forEach((childId) => visit(childId, depth + 1));
    }
  }

  props.state.rootIds.forEach((nodeId) => visit(nodeId, 1));
  return visible;
});

const visibleIds = computed(
  () => new Set(rows.value.map(({ node }) => node.id)),
);

const rovingFocusId = computed(() =>
  visibleIds.value.has(props.focusedId)
    ? props.focusedId
    : rows.value[0]?.node.id,
);

watch(
  () => props.insertedIds,
  (inserted) => {
    if (inserted.size === 0) {
      return;
    }
    const next = new Set(expandedIds.value);
    inserted.forEach((insertedId) => {
      let node = props.state.nodes[insertedId];
      while (node?.parentId) {
        next.add(node.parentId);
        node = props.state.nodes[node.parentId];
      }
    });
    expandedIds.value = next;
  },
);

function setRowElement(
  nodeId: string,
  element: Element | ComponentPublicInstance | null,
): void {
  if (element instanceof HTMLElement) {
    rowElements.set(nodeId, element);
  } else {
    rowElements.delete(nodeId);
  }
}

function toggle(nodeId: string): void {
  const next = new Set(expandedIds.value);
  if (next.has(nodeId)) {
    next.delete(nodeId);
  } else {
    next.add(nodeId);
  }
  expandedIds.value = next;
}

async function focusRow(nodeId: string | undefined): Promise<void> {
  if (!nodeId) {
    return;
  }
  emit("focusChange", nodeId);
  await nextTick();
  rowElements.get(nodeId)?.focus();
}

function selectRow(nodeId: string, event: MouseEvent): void {
  emit("select", nodeId);
  emit("focusChange", nodeId);
  (event.currentTarget as HTMLElement).focus();
}

function handleKey(event: KeyboardEvent, row: VisibleRow): void {
  const index = rows.value.findIndex(({ node }) => node.id === row.node.id);
  if (index < 0) {
    return;
  }

  let targetId: string | undefined;
  if (event.key === "ArrowDown") {
    targetId = rows.value[Math.min(index + 1, rows.value.length - 1)]?.node.id;
  } else if (event.key === "ArrowUp") {
    targetId = rows.value[Math.max(index - 1, 0)]?.node.id;
  } else if (event.key === "Home") {
    targetId = rows.value[0]?.node.id;
  } else if (event.key === "End") {
    targetId = rows.value.at(-1)?.node.id;
  } else if (event.key === "ArrowRight" && row.node.childIds.length > 0) {
    if (!row.expanded) {
      toggle(row.node.id);
    } else {
      targetId = rows.value[index + 1]?.node.id;
    }
  } else if (event.key === "ArrowLeft") {
    if (row.expanded && row.node.childIds.length > 0) {
      toggle(row.node.id);
    } else if (row.node.parentId && visibleIds.value.has(row.node.parentId)) {
      targetId = row.node.parentId;
    }
  } else if (event.key === "Enter" || event.key === " ") {
    emit("select", row.node.id);
  } else {
    return;
  }

  event.preventDefault();
  if (targetId) {
    void focusRow(targetId);
  }
}

function severityIcon(node: TreeNode) {
  if (node.severity === "error" || node.severity === "blocked") {
    return AlertCircle;
  }
  if (node.severity === "warning") {
    return AlertTriangle;
  }
  if (node.severity === "running") {
    return CircleDashed;
  }
  if (node.severity === "changed") {
    return FileSliders;
  }
  if (node.kind === "section" || node.kind === "group") {
    return Folder;
  }
  if (node.kind === "resource") {
    return Workflow;
  }
  return CheckCircle2;
}

function accessibleLabel(node: TreeNode): string {
  return [
    node.label,
    node.phase,
    node.valueSummary,
    node.severity !== "normal" ? node.severity : undefined,
  ]
    .filter(Boolean)
    .join(", ");
}
</script>

<template>
  <section class="tree-panel" aria-label="Resources">
    <div class="tree-heading">
      <div>
        <span class="eyebrow">Resources</span>
        <h2>Migration workflow</h2>
      </div>
      <span class="mode-badge" :class="{ editing: state.mode === 'edit' }">
        {{ state.mode === "edit" ? "Editing" : "Inspecting" }}
      </span>
    </div>

    <label class="tree-filter">
      <Search :size="16" aria-hidden="true" />
      <span class="sr-only">Filter resources</span>
      <input v-model="filter" type="search" placeholder="Filter resources">
    </label>

    <div class="tree-scroll">
      <TransitionGroup
        tag="div"
        name="tree-row"
        class="resource-tree"
        role="tree"
        aria-label="Workflow resources"
      >
        <div
          v-for="(row, index) in rows"
          :id="`tree-row-${row.node.id}`"
          :key="row.node.id"
          :ref="(element) => setRowElement(row.node.id, element)"
          class="tree-row"
          role="treeitem"
          :aria-label="accessibleLabel(row.node)"
          :aria-level="row.depth"
          :aria-posinset="index + 1"
          :aria-setsize="rows.length"
          :aria-expanded="row.node.childIds.length > 0 ? row.expanded : undefined"
          :aria-selected="selectedId === row.node.id"
          :data-node-id="row.node.id"
          :data-severity="row.node.severity"
          :data-inserted="insertedIds.has(row.node.id) || undefined"
          :tabindex="rovingFocusId === row.node.id ? 0 : -1"
          :style="{ '--tree-depth': row.depth }"
          @click="selectRow(row.node.id, $event)"
          @focus="emit('focusChange', row.node.id)"
          @keydown="handleKey($event, row)"
        >
          <button
            class="tree-expander"
            type="button"
            tabindex="-1"
            :disabled="row.node.childIds.length === 0"
            :aria-label="`${row.expanded ? 'Collapse' : 'Expand'} ${row.node.label}`"
            @mousedown.prevent
            @click.stop="toggle(row.node.id)"
          >
            <ChevronRight
              v-if="row.node.childIds.length > 0"
              :size="15"
              :class="{ open: row.expanded }"
              aria-hidden="true"
            />
          </button>
          <span class="tree-icon" aria-hidden="true">
            <component
              :is="severityIcon(row.node)"
              :size="16"
              :class="{ spinning: row.node.severity === 'running' }"
            />
          </span>
          <span class="tree-copy">
            <span class="tree-label">{{ row.node.label }}</span>
            <span v-if="row.node.phase || row.node.valueSummary" class="tree-meta">
              {{ [row.node.phase, row.node.valueSummary].filter(Boolean).join(" · ") }}
            </span>
          </span>
          <span
            v-if="row.node.severity !== 'normal'"
            class="severity-dot"
            aria-hidden="true"
          />
        </div>
      </TransitionGroup>
      <div v-if="rows.length === 0" class="tree-empty">
        No resources match "{{ filter }}".
      </div>
    </div>

    <footer class="tree-footer">
      <span>{{ Object.keys(state.nodes).length }} nodes · r{{ state.revision }}</span>
      <span>Arrow keys navigate</span>
    </footer>
  </section>
</template>
